# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Webhook

# name of GitHub event that triggers workflow
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch
# on: [repository_dispatch]

# it's possible to filter whole workflow using custom type sent, eg: from ValidateSet here:
# https://github.com/adamrushuk/github-actions/blob/master/TriggerCustomAction.ps1#L33
on:
  repository_dispatch:
    types: [test]

# global environment variables
# https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
env:
  MY_WORKFLOW_VAR: work

  # UNSUPPORTED: Cannot concatenante at Workflow level
  # MY_WORKFLOW_VAR2: ${{ env.MY_WORKFLOW_VAR }}-workvalue01

jobs:
  build:

    # always pin versions
    # # view installed software: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
    runs-on: ubuntu-18.04

    env:
      MY_JOB_VAR: job

      # UNSUPPORTED: Cannot concatenante at Job level
      # MY_WORK_JOB_VAR: ${{ env.MY_WORKFLOW_VAR }}

    steps:
    # Checkout
    - uses: actions/checkout@v2

    # Show event info
    - name: Show triggered event data
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: pwsh -command "./scripts/Get-EventData.ps1"

    # WORKAROUND Env var concatenation
    # https://github.community/t5/GitHub-Actions/How-can-we-concatenate-multiple-env-vars-at-workflow-and-job/td-p/48489
    - name: BASH - Concatenate env vars (Workaround)
      run: |
        echo ::set-env name=MY_CONCATENATED_BASH_VAR::${{ env.MY_WORKFLOW_VAR }}-${{ env.MY_JOB_VAR }}-bash-stepvalue01

    - name: PWSH - Concatenate env vars (Workaround)
      # override the default bash shell, as running on ubuntu
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
      shell: pwsh
      # pwsh requires double quotes when setting env vars
      run: |
        echo "::set-env name=MY_CONCATENATED_PWSH_VAR::${{ env.MY_WORKFLOW_VAR }}-${{ env.MY_JOB_VAR }}-pwsh-stepvalue01"

    - name: Output event data
      shell: pwsh
      env:
        MY_STEP_VAR: step
      run: |
        # Env var concatenation
        Write-Output "MY_WORKFLOW_VAR is: [$env:MY_WORKFLOW_VAR]"
        Write-Output "MY_JOB_VAR is: [$env:MY_JOB_VAR]"
        Write-Output "MY_STEP_VAR is: [$env:MY_STEP_VAR]"
        Write-Output "MY_CONCATENATED_BASH_VAR is: [$env:MY_CONCATENATED_BASH_VAR]"
        Write-Output "MY_CONCATENATED_PWSH_VAR is: [$env:MY_CONCATENATED_PWSH_VAR]"
